---
- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: install packages
    package:
      name:
        - htop
        - git
        - terminator
        - emacs

  - name: install docker dependencies
    package:
      name:
        - bc
        - curl
        - expect
        - git
        - ca-certificates

  - name: Create Docker GPG key directory
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: "0755"

  - name: Download Docker's official GPG key
    get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: "0644"
      
  - name: Add Docker repository to Apt sources
    apt_repository:
      repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present
      filename: docker
      
  - name: Update apt cache after adding Docker repository
    apt:
      update_cache: yes
      
  - name: Install Docker and Docker Compose
    package:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present
      
  - name: Ensure Docker service is enabled and started
    service:
      name: docker
      state: started
      enabled: yes

  - name: Add ubuntu user to docker group
    user:
      name: ubuntu
      groups: docker
      append: yes

  - name: install openvpn
    package:
      name: openvpn    


  - name: Install zsh
    ansible.builtin.package:
      name: zsh
      state: present
    become: true
  - name: Set user shell to zsh
    ansible.builtin.user:
      name: "{{ ansible_user_id }}"
      shell: /bin/zsh
    become: true
  - name: Download ohmyzsh
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: "/tmp/install_oh_my_zsh.sh"
      mode: '0755'
  - name: Install ohmyzsh
    ansible.builtin.script:
      cmd: "/tmp/install_oh_my_zsh.sh"
  - name: Install PowerLevel10K
    ansible.builtin.git:
      repo: https://github.com/romkatv/powerlevel10k.git
      dest: "/home/{{ ansible_user_id }}/.oh-my-zsh/custom/themes/powerlevel10k"
      depth: 1
  - name: Download NerdFonts
    ansible.builtin.get_url:
      url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Meslo.zip
      dest: "/home/{{ ansible_user_id }}/Meslo.zip"
  - name: Create temp directory
    ansible.builtin.file:
      path: "/home/{{ ansible_user_id }}/Meslo"
      state: directory
      mode: '0755'
  - name: Install font files
    ansible.builtin.unarchive:
      src: "/home/{{ ansible_user_id }}/Meslo.zip"
      dest: "/home/{{ ansible_user_id }}/Meslo"
  - name: Move font files to fonts directory
    ansible.builtin.copy:
      src: "/home/{{ ansible_user_id }}/Meslo"
      dest: /usr/share/fonts/Meslo
      owner: root
    become: true
  - name: Update .zshrc
    ansible.builtin.lineinfile:
      path: "/home/{{ ansible_user_id }}/.zshrc"
      insertafter: EOF
      line: "source /home/{{ ansible_user_id }}/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme"
