---
- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: install packages
    package:
      name:
        - htop
        - git
        - terminator
        - emacs
        - zsh
        - ripgrep
        - fzf

  - name: install docker dependencies
    package:
      name:
        - bc
        - curl
        - expect
        - git
        - ca-certificates

  - name: Create Docker GPG key directory
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: "0755"

  - name: Download Docker's official GPG key
    get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: "0644"
      
  - name: Add Docker repository to Apt sources
    apt_repository:
      repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present
      filename: docker
      
  - name: Update apt cache after adding Docker repository
    apt:
      update_cache: yes
      
  - name: Install Docker and Docker Compose
    package:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present
      
  - name: Ensure Docker service is enabled and started
    service:
      name: docker
      state: started
      enabled: yes

  - name: Add ubuntu user to docker group
    become: yes
    user:
      name: "{{ ansible_facts['env']['SUDO_USER'] }}"
      groups: docker
      append: yes

  - name: install openvpn
    package:
      name: openvpn

  - name: Install Oh My Zsh # noqa: latest
    ansible.builtin.git:
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: ~/.oh-my-zsh
      depth: 1
  
  - name: Install zsh-autosuggestions plugin # noqa: latest
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      depth: 1
  
  - name: Install zsh-completions plugin # noqa: latest
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-completions
      dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
      depth: 1
  
  - name: Install zsh-syntax-highlighting plugin # noqa: latest
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
      depth: 1

  - name: Install Powerline10k theme # noqa: latest
    ansible.builtin.git:
      repo: https://github.com/romkatv/powerlevel10k.git
      dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
      depth: 1
  
  - name: Change user shell to zsh 
    become: true
    ansible.builtin.user:
      name: "{{ ansible_facts['env']['SUDO_USER'] }}"
      shell: /bin/zsh

  - name: Install nvm
    shell: >
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
    args:
      executable: /bin/bash
      chdir: "{{ ansible_env.HOME }}"
      creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

  - name: Loads nvm for the current shell
    shell: >
      export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

  - name: Install node and set version
    shell: >
      /bin/bash -c "source ~/.nvm/nvm.sh && nvm install 0.20 && nvm alias default 0.20"
      creates=/home/{{ ansible_facts['env']['SUDO_USER']  }}/.nvm/alias
